apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sample-app-rollout
  namespace: blue-green-demo
spec:
  replicas: 5
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: web
        image: quay.io/ubiowororuki/mypython-app:latest 
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
  strategy:
    canary:
      steps:
      - setWeight: 20   
      - pause: {}      
      - setWeight: 60  
      - pause:
          duration: 30s
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-active
  namespace: blue-green-demo
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  selector:
    app: sample-app
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-preview
  namespace: blue-green-demo
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  selector:
    app: sample-app
