apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: quickbite
type: Opaque
stringData:
  postgres-user: admin
  postgres-password: admin
  postgres-db: quickbite_db
  database-url: postgresql://admin:admin@postgres:5432/quickbite_db
