server.port=8081

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_DB:quickbite_db}
spring.datasource.username=${DATABASE_USERNAME:quickbite_user}
spring.datasource.password=${DATABASE_PASSWORD:quickbite_secure_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
