apiVersion: v1
kind: Service
metadata:
  name: quickbite-app
  namespace: dev
spec:
  selector:
    app: quickbite-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
