apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickbite-app-dev
  namespace: dev
  labels:
    app: quickbite-app-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quickbite-app-dev
  template:
    metadata:
      labels:
        app: quickbite-app-dev
    spec:
      containers:
      - name: app
        image:  rukevweubio/quickbite:latest

        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: database-url
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
