apiVersion: v1
kind: Service
metadata:
  name: quickbite-app-stage
  namespace: stage
spec:
  selector:
    app: quickbite-app-stage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
