name:  gitaction workflow  build and deploy to aks 

on:
  push:
    branches:
      - qa-engineer
    paths:
      - "Dockerfile"
      - "src/**"
      - ".github/workflows/devsecops-pipeline*"
      - "server.ts"

jobs:
  gitleaks-docker:
    name: gitleaks-docker-scan
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gitleaks Scan
        run: |
          echo "🔍 Running Gitleaks scan using Docker..."
          docker run --rm \
            -v "${{ github.workspace }}:/path" \
            zricethezav/gitleaks:latest detect \
            --source=/path \
            --verbose \
            --report-format=json \
            --report-path=/path/gitleaks-report.json \
            --redact \
            --exit-code 1

      - name: Upload Gitleaks Report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json

  checkov_scan_terraform:
   name: Terraform Security Scan (Checkov)
   needs: gitleaks-docker
   runs-on: ubuntu-latest
   steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov on Terraform
        run: |
          checkov \
            -d ./ \
            --framework terraform \
            --output json \
            > checkov-terraform-report.json || true

      - name: Upload Checkov Terraform Report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-terraform-report
          path: checkov-terraform-report.json
